server: # default port 설정 (localhost:8000/ .....)
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .html

  # spring static file path
  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false # 개발 시 새로고침하면 적용됨

  #  mysql 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # entity 만들때 변수명 그대로 테이블 생성
      use-new-id-generator-mappings: false # jpa의 numbering 전략을 사용하지 않음
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

decorator:
  datasource:
    p6spy:
      enable-logging: true